-- ==============================================================================
-- PALMORA SUPABASE SCHEMA
-- Run this script in your Supabase SQL Editor to set up the backend database.
-- ==============================================================================

-- 1. PROFILES TABLE (Extends Supabase Auth mapped to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id );

-- Optional: trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. PLANTS TABLE (A user's planted crops and devices)
CREATE TABLE IF NOT EXISTS public.plants (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  cycle_days INTEGER NOT NULL DEFAULT 90,
  photo_url TEXT,
  planted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for plants
ALTER TABLE public.plants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own plants" ON public.plants;
CREATE POLICY "Users can view their own plants"
  ON public.plants FOR SELECT
  USING ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Users can insert their own plants" ON public.plants;
CREATE POLICY "Users can insert their own plants"
  ON public.plants FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Users can update their own plants" ON public.plants;
CREATE POLICY "Users can update their own plants"
  ON public.plants FOR UPDATE
  USING ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Users can delete their own plants" ON public.plants;
CREATE POLICY "Users can delete their own plants"
  ON public.plants FOR DELETE
  USING ( auth.uid() = user_id );


-- 3. SENSOR_DATA TABLE (Telemetry from IoT Nodes)
-- (Typically high insertion rate; could be migrated to TimescaleDB later if needed)
CREATE TABLE IF NOT EXISTS public.sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_id UUID REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
  soil_moisture REAL NOT NULL,
  temperature REAL NOT NULL,
  humidity REAL NOT NULL,
  uv_index REAL NOT NULL,
  wind_speed REAL NOT NULL,
  health_score REAL NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for efficient time-series querying
CREATE INDEX IF NOT EXISTS idx_sensor_data_plant_time ON public.sensor_data(plant_id, created_at DESC);

-- RLS for sensor_data
ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;

-- Assuming IoT nodes insert data securely (e.g., via Edge Function or secure service key).
-- For now, we allow authenticated users to view telemetry for their plants.
DROP POLICY IF EXISTS "Users can view telemetry for their plants" ON public.sensor_data;
CREATE POLICY "Users can view telemetry for their plants"
  ON public.sensor_data FOR SELECT
  USING ( 
    EXISTS (
      SELECT 1 FROM public.plants 
      WHERE public.plants.id = public.sensor_data.plant_id 
      AND public.plants.user_id = auth.uid()
    )
  );

-- For testing purposes, we might allow authenticated users to insert dummy data
DROP POLICY IF EXISTS "Users can insert telemetry for their plants" ON public.sensor_data;
CREATE POLICY "Users can insert telemetry for their plants"
  ON public.sensor_data FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.plants 
      WHERE public.plants.id = public.sensor_data.plant_id 
      AND public.plants.user_id = auth.uid()
    )
  );


-- 4. ALERTS TABLE (Notification logs)
CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  plant_id UUID REFERENCES public.plants(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  type TEXT NOT NULL, -- e.g., 'warning', 'danger', 'info', 'success'
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS for alerts
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view alerts for their plants" ON public.alerts;
CREATE POLICY "Users can view alerts for their plants"
  ON public.alerts FOR SELECT
  USING ( 
    EXISTS (
      SELECT 1 FROM public.plants 
      WHERE public.plants.id = public.alerts.plant_id 
      AND public.plants.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Users can update alerts for their plants (mark as read)" ON public.alerts;
CREATE POLICY "Users can update alerts for their plants (mark as read)"
  ON public.alerts FOR UPDATE
  USING ( 
    EXISTS (
      SELECT 1 FROM public.plants 
      WHERE public.plants.id = public.alerts.plant_id 
      AND public.plants.user_id = auth.uid()
    )
  );
